apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gophprofile.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
data:
  HOST: {{ .Values.config.host | quote }}
  PORT: {{ .Values.config.port | quote }}
  MAX_FILE_SIZE: {{ .Values.config.maxFileSize | quote }}
  MINIO_ENDPOINT: {{ .Values.config.minioEndpoint | quote }}
  MINIO_BUCKET_NAME: {{ .Values.config.minioBucketName | quote }}
  MINIO_USE_SSL: {{ .Values.config.minioUseSSL | quote }}
  RABBITMQ_HOST: {{ .Values.config.rabbitmqHost | quote }}
  RABBITMQ_PORT: {{ .Values.config.rabbitmqPort | quote }}
  RABBITMQ_USER: {{ .Values.config.rabbitmqUser | quote }}
  RABBITMQ_VHOST: {{ .Values.config.rabbitmqVHost | quote }}
  RATE_LIMIT_ENABLED: {{ .Values.config.rateLimitEnabled | quote }}
  RATE_LIMIT_RPS: {{ .Values.config.rateLimitRPS | quote }}
  RATE_LIMIT_BURST: {{ .Values.config.rateLimitBurst | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  LOG_FORMAT: {{ .Values.config.logFormat | quote }}
  RUN_MIGRATIONS: {{ .Values.config.runMigrations | quote }}
  OTEL_ENABLED: {{ .Values.config.otelEnabled | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.config.otelExporterEndpoint | quote }}
  OTEL_SERVICE_NAME: {{ .Values.config.otelServiceNameServer | quote }}
  METRICS_ADDR: {{ .Values.config.metricsAddr | quote }}
  AUDIT_FILE: {{ .Values.config.auditFile | quote }}
  SWAGGER_ENABLED: {{ .Values.config.swaggerEnabled | quote }}
  GIN_MODE: release
