{{- if .Values.hpa.server.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "gophprofile.fullname" . }}-server-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gophprofile.server.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "gophprofile.fullname" . }}-server
  minReplicas: {{ .Values.hpa.server.minReplicas }}
  maxReplicas: {{ .Values.hpa.server.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.server.targetCPUUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.server.targetMemoryUtilization }}
{{- end }}
---
{{- if .Values.hpa.worker.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "gophprofile.fullname" . }}-worker-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gophprofile.worker.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "gophprofile.fullname" . }}-worker
  minReplicas: {{ .Values.hpa.worker.minReplicas }}
  maxReplicas: {{ .Values.hpa.worker.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.worker.targetCPUUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.worker.targetMemoryUtilization }}
{{- end }}
