apiVersion: v1
kind: Service
metadata:
  name: {{ include "gophprofile.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gophprofile.server.labels" . | nindent 4 }}
spec:
  selector:
    app: gophprofile-server
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.server.service.port }}
      targetPort: http
    - name: metrics
      port: {{ .Values.server.service.metricsPort }}
      targetPort: metrics
  type: ClusterIP
