apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init-bucket
  namespace: database
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: minio/mc:latest
          envFrom:
            - secretRef:
                name: minio-secrets
          command:
            - /bin/sh
            - -c
            - |
              mc alias set local http://minio.database.svc.cluster.local:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"
              mc mb --ignore-existing local/gophprofile
              echo "Bucket gophprofile ready"
